// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1APDAWNfSXOO8UE8a2DkNAPq0_Aa4gpw',
    appId: '1:137389838930:web:bff89ea8d3a1448b84458b',
    messagingSenderId: '137389838930',
    projectId: 'horas-v3-273d9',
    authDomain: 'horas-v3-273d9.firebaseapp.com',
    storageBucket: 'horas-v3-273d9.firebasestorage.app',
    measurementId: 'G-28PYS9TE3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZB9H_EhqTk052PDoY0imygGVwTv5PRM',
    appId: '1:137389838930:android:a955edabd9db458b84458b',
    messagingSenderId: '137389838930',
    projectId: 'horas-v3-273d9',
    storageBucket: 'horas-v3-273d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hLqrces8nvwvwMv9aD_mpSONw6Dh4t4',
    appId: '1:137389838930:ios:6b11f61205d9e24284458b',
    messagingSenderId: '137389838930',
    projectId: 'horas-v3-273d9',
    storageBucket: 'horas-v3-273d9.firebasestorage.app',
    iosBundleId: 'com.example.horasV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1APDAWNfSXOO8UE8a2DkNAPq0_Aa4gpw',
    appId: '1:137389838930:web:0795b4d956088d6484458b',
    messagingSenderId: '137389838930',
    projectId: 'horas-v3-273d9',
    authDomain: 'horas-v3-273d9.firebaseapp.com',
    storageBucket: 'horas-v3-273d9.firebasestorage.app',
    measurementId: 'G-8L6K9ES47B',
  );

}